sudo: false
language: python

install: pip install tox wheel

matrix:
  include:
    - python: 3.6
      env: TOX_ENV=py36
    - python: 3.5.6
      env: TOX_ENV=py35
    - python: 3.6
      env: TOX_ENV=pep8
    - python: 3.7
        env: TOX_ENV=py37

script:
    - tox -e $TOX_ENV

before_deploy:
    - bin/ihrpi-build

deploy:
  provider: releases
  api_key:
    secure: "UCRWPTHQfgDKIaYfOUrxPOOXqa0Qs7UKYOYWj4RhrU+0wn70AHL9oT01wEj25es+QN1u/q6K95vgyLLEEG/C+RDduY0nzDhRrwjfPP4ofBxCzJl19fiZ2AZVz21OWaScVZViPSOV0SR0F5qewe1WbOlwd6GGjblJuZtJiOZz0aPsoa4XP3LPsQ7D1OCU9Z0sKpp+V+1sq3vxP42SL1/jxc78ouXhCMP7GmlfeE2U8f+gbGvGr0soLvhQi2lFfPpdA1S5M6hx4AnjjfTp1zkrQ90+EuamQFeQ9SZbwTgzfT1qv88AUh9gddzLoX8pFIK7vbiOmUpllU1Ao5+ldSCz/4JfQ4UvZ56kDxrk560p7WJDT2YZL3CrJWNlUaFjXkiAmk3kl6f8m6XhFn3ZuHBH0ygXeXebpUdCAisalpawyweWE7t+hIK6zN60oqt96BOaYruTJpZP1Tmgi//Lp9Zd6QBdnjhlxthuUYvTKm/d03r8KdPo8dF2iVocjypV4D9c38REc7K7NffOEIT+tpsDUlt/aCEar9eF0EKzHIiTFEgenrqZPuxwIcKdBCmpSIuJV9x/OqCSUFXjSVaOSPBSAaGSBNHp2fIDWy1RUAH6zLIYBXfZ1C63cmF0S2mc5Mrp5aDzijHHlh/uCpQOu3P27oP3zTzzZvaBGiePn4TNWpk="
  skip_cleanup: true
  file_glob: true
  file:
      - dist/ihrpi-*.whl
  on:
    tags: true
    branch: master
    repo: iheartradio/ihrpi
