name: Python Pull Request
on:
  pull_request_target:
    types: [opened, synchronize, reopened, closed]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  run_tests:
    name: Run Python Tests
    uses: ./.github/workflows/run_tests.yml
    with:
      branch: ${{ github.event.pull_request.head.sha }}
